on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  make:
    name: Building OS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Watcom
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/open-watcom-v2_2022-01-10_64bit.7z
          sudo apt-get install -y p7zip-full
          7z x open-watcom-v2_2022-01-10_64bit.7z -o/opt/open-watcom
          sudo ln -s /opt/open-watcom /usr/local/watcom
          echo 'export PATH=$PATH:/usr/local/watcom/binl64' >> $GITHUB_ENV

      - name: Install NASM
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Create build directory
        run: mkdir -p build

      - name: Build OS
        run: make
